Enhancement: Allow org block live sync
nobiot/org-transclusion pull request #176
Opened 2023-03-12 10:01 UTC by devcarbon-com

Draft pull request.  Preliminary manual testing has been successful. 

Not sure when org started support for it, but it works with 9.7-pre, and hopefully 9.6 also.

2023-03-15 00:32 UTC, devcarbon-com commented
This seems to work okay, but I feel like it's a bit hacky and solving the problem at the wrong location. 

I think it would be better to add 2 more markers to the text properties in the case of org blocks.

Right now, we have `org-transclusion-beg-mkr` and `org-transclusion-end-mkr` that covers the whole range of the content added when the transclusion is expanded.  But these do not distinguish between exact content, and modified content (IE. when we add `#begin_src lang` and `#end_src`). 

One way to do this without having to change a lot of other code would be to add text properties specifying the orginal content range when we modify the `src-content` in  `org-transclusion-content-src-lines` and then in `org-transclusion-content-insert` to extract them from `content` and add markers.


I have a proof-of-concept of this locally on my machine, but I'm not aware of how to best proceed when it comes to pull requests that become inter-dependent. 

@nobiot Should I just add it as it's own request, and then merge this (#176) and #157 after it's accepted?

2023-03-21 00:11 UTC, devcarbon-com commented
@nobiot Sure thing!

I'm happy to add a code example if you would like. Sometimes it's easier to read code than English :P.

2023-03-25 21:53 UTC, nobiot commented
Sorry, I think I do not seem to have understood the intent of this PR.
See below... I try starting live-sync with the test files below; no change of behaviour.

It will be great if you could provide some example files.

![image](https://user-images.githubusercontent.com/12507865/227743964-53739134-00a6-4aad-8d80-0c72954842be.png)


``` org
#test-live-sync.org
#+transclude: [[file:test-src.org::code]]
```

``` org
#test-src.org
#+name: code
#+begin_src emacs-lisp transclude file:simple.el :lines 1-10 -n  -r
         (save-excursion                 ;; (ref:sc)
            (goto-char (point-min))
            (message "executed."))     ;; (ref:jump)
#+end_src
```

2023-03-25 22:18 UTC, devcarbon-com commented
Oh I had not tried transcluding code from another org file.  I'd need to do some digging to figure out how to do that. 

What I have been doing is like this:

Narrative.org
```elisp
#+transclude: [[file:code.el]]  :src elisp
```
code.el
```elisp
(defun hello ()
  (message "hello"))
```

2023-03-27 17:51 UTC, nobiot commented
Oh, now I got it!
All what I said in [this discussion thread](https://github.com/nobiot/org-transclusion/discussions/114#discussioncomment-5201326) is about transcluding a source code block from another Org file -- i.e. the source being another Org file. 

The use case for this PR is transcluding a text file, it is not applicable -- I'm sure you figured that out.

I have tested the code lightly with my test python files (I should perhaps put into the repo as a common test file set). Your code change works extremely well as far as I could see -- I could even use `org-edit-src` when live-sync is on. Whoa. 

The reason why I didn't let it work by this:

```
(when (string= "src" type)
  (user-error "No live sync for src-code block"))
```

is that I could not work out a reliable way to deal with the indentation -- the length of the source and transclusion must exactly the same -- I think you have figured out a way.

2023-03-27 17:55 UTC, nobiot commented
There is one suggestion, if I may. I will write it directly in the review of the source code as well.  Could you look into moving the change you made in function `org-transclusion-live-sync-buffers-others-default` to function `org-transclusion-live-sync-buffers-src-lines` in file `org-transclusion-src-lines.el` by any chance? This way:

1. We can contain the change for "src" type transclusion to a function
2. Probably you can remove `(if (org-in-src-block-p)` clause (because "src" type always results in the source text file be in a src block

What do you think?

2023-03-27 18:01 UTC, nobiot requested changes
If you could consider the change I suggested, that will be great. I have a feeling it should be merged as soon as you let me know the suggested change is not feasible, or you have changed it according my suggestion -- I am really hoping that the suggested change is feasible...

2023-03-27 18:09 UTC, devcarbon-com commented on org-transclusion.el
> +      ;; Return t if 'wrap-prefix is already in `yank-excluded-properties'
Oh oops, yes that is exactly all it is.  I must have bumped it somehow.   I probably should disable aggressive indent while working on pull requests. Or maybe figure out a way to make it match the style already used in the file.

2023-03-27 18:09 UTC, devcarbon-com commented on org-transclusion.el
> +              (tc-ov (if (org-in-src-block-p)
I'll give it a shot!  :)

2023-03-27 18:12 UTC, nobiot commented on org-transclusion.el
> +      ;; Return t if 'wrap-prefix is already in `yank-excluded-properties'
No worries :)

2023-03-27 18:27 UTC, devcarbon-com commented
@nobiot Oh, I thought I just had to check the box, so I'm glad you brought it up!

Got it started now.

2023-03-27 18:33 UTC, nobiot commented
Thank you!

2023-03-27 21:04 UTC, nobiot commented
> That's definitely doable, but I'm not sure how in elisp do that without it being rather verbose, so I wrote a macro that I personally use a lot, but I'm not sure it would be a good idea to use in production code. (I'm a elisp newbie).

I have an idea; a simple one without a macro. Let me get back to you as a suggestion. Please give me until the end of the week (I am hoping to have some time tomorrow but if it fails I need a bit more time).

2023-03-28 20:25 UTC, nobiot commented
@devcarbon-com I have no idea how I can send a commit to your PR so I opened a new one as continuation #178. Your original commits are there, too. Could you take a look? 

To be honest, I don't understand the "dot" syntax you show here: `(+ .a .b .c)` and how the macro works (I'm not familiar with `let-alist`. 

My suggestion is simple and probably crude compared to your macro-based way: it is just to run the default function to create the src-ov and tc-ov, and o move tc-ov's location based on your offset logic... Kinda avoids "repeating yourself" issue, I guess. But not sophisticated. Perhaps this is sufficient?

Let me know of your thoughts...  At least, functionally it seems to works in the same way as yours. 

```
(defun do-the-work ()
  (alist-of-let* ((a 1)
                  (b 2)
                  (c (- b a))))

(defun delegate-the-work ()
  (let-alist (do-the-work)
    (+ .a .b .c)))

(delegate-the-work) ;=> 4
```

2023-03-29 20:21 UTC, merged